# Kind.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes: 
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: initConfiguration
        nodeRegistration:
        kubeletExtractArgs:
          node-labels: "CriticalAddonsOnly=true, eks-k8s-version=1.29"
      
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtractArgs:
            node-labels: "CriticalAddonsOnly=true, eks-k8s-version=1.29"
  
  - role: worker
    labels:
      "CriticalAddonsOnly": "true"
      "eks-k8s-version": "1.29"